stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-latest'
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"
- stage: Dev_Deploy
  jobs:
  - deployment: dev_deploy
    pool:
      vmImage: 'Ubuntu-latest'
    environment: ''
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, dev world !!!"
- stage: Deploy
  jobs:
  - deployment: 
    pool:
      vmImage: 'Ubuntu-latest'
    environment: ''
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, deploy world !!!"
